mnist_files:
- train-images-idx3-ubyte.gz
- train-labels-idx1-ubyte.gz
- t10k-images-idx3-ubyte.gz
- t10k-labels-idx1-ubyte.gz
mnist_compressed_data_path: data/compressed
mnist_raw_data_path: data/raw
processed_image_path: data/processed_images